package ca.corbett.extras.properties;

import ca.corbett.forms.fields.FormField;

/**
 * Can be used with AbstractProperty and its implementing classes to listen for FormField generation.
 * This allows you to customize the generated FormField after it has been created but before it has
 * been supplied to whoever requested it (the application config dialog typically). This allows you
 * to apply customizations to the generated FormField in ways that are perhaps not supported by the
 * wrapping methods provided by the containing AbstractProperty. For example, applying particular
 * margins to the generatedFormField, or changing its font or color properties.
 *
 * @author <a href="https://github.com/scorbo2">scorbo2</a>
 * @since swing-extras 2.5
 */
@FunctionalInterface
public interface FormFieldGenerationListener {

    /**
     * Fired after the given AbstractProperty has generated the FormField, but before the
     * generated FormField has been supplied to whatever requested it (the application config
     * dialog typically). Customizations are possible on the generated FormField if needed.
     * <p>
     * <b>Note:</b> you cannot change the FormField's identifier with this hook. The
     * containing property will overwrite whatever identifier you try to set here.
     * This is deliberate, to preserve the linkage between the generated FormField
     * and the AbstractProperty that created it.
     * </p>
     * <p>
     * <b>Should I use this method if I want to add a change listener to the FormField?</b>
     * No, you should strongly consider using AbstractProperty.addFormFieldChangeListener()
     * instead, because that hook will give your listener additional context that you won't
     * get here, such as the FormPanel on which the FormField is located. This hook is
     * intended more for cosmetic tweaks on the generated FormField that you can't make
     * via the wrapper methods in AbstractProperty, such as setting custom colors/fonts, etc.
     * </p>
     *
     * @param property  The AbstractProperty implementation that has generated the FormField.
     * @param formField The FormField instance that was generated by the AbstractProperty.
     */
    void formFieldGenerated(AbstractProperty property, FormField formField);
}
