package ca.corbett.extras.properties;

import ca.corbett.forms.FormPanel;
import ca.corbett.forms.fields.FormField;

import java.awt.event.ActionEvent;

/**
 * Used by PropertyFormFieldChangeListener to indicate that a change has been made in a FormField
 * that was created and is managed by some AbstractProperty instance. This class contains information
 * about which FormField on which AbstractProperty was modified, and on which FormPanel the change happened.
 * <p>
 *     <B>IMPORTANT NOTE:</B> Objects of this class contain both the AbstractProperty that generated the
 *     FormField, and also the FormField itself. Keep in mind that these change events are fired while
 *     the FormPanel in question is visible and has not yet been OK'd by the user!
 *     That means, the property in question has not yet been informed of the
 *     changes made in the form field. That means, if you wish to read the current version of the FormField,
 *     you should interrogate the FormField and <B>NOT</B> the AbstractProperty! If you want to know
 *     what the value of the field was at the time that it was generated by the AbstractProperty,
 *     then query the AbstractProperty, and not the FormField.
 * </p>
 *
 * @since swing-extras 2.3
 * @author <a href="https://github.com/scorbo2">scorbo2</a>
 */
public class PropertyFormFieldValueChangedEvent {
    private final ActionEvent sourceEvent;
    private final FormPanel formPanel;
    private final FormField formField;
    private final AbstractProperty property;

    public PropertyFormFieldValueChangedEvent(AbstractProperty owner, ActionEvent sourceEvent, FormPanel formPanel, FormField formField) {
        this.sourceEvent = sourceEvent;
        this.formField = formField;
        this.formPanel = formPanel;
        this.property = owner;
    }

    public ActionEvent getSourceEvent() {
        return sourceEvent;
    }

    public FormPanel getFormPanel() {
        return formPanel;
    }

    public FormField getFormField() {
        return formField;
    }

    public AbstractProperty getProperty() {
        return property;
    }
}
