package ca.corbett.extras.properties.dialog;

import ca.corbett.extras.ScrollUtil;
import ca.corbett.extras.ToggleableTabbedPane;
import ca.corbett.extras.properties.AbstractProperty;
import ca.corbett.extras.properties.LabelProperty;
import ca.corbett.extras.properties.PropertiesManager;
import ca.corbett.forms.FormPanel;
import ca.corbett.forms.fields.FormField;

import java.awt.BorderLayout;
import java.awt.Window;
import java.util.List;
import java.util.logging.Logger;

/**
 * An internal class used to generate the "classic" properties dialog,
 * with a separate tab for each major category of properties, and
 * header labels used to separate the subcategories.
 *
 * @author <a href="https://github.com/scorbo2">scorbo2</a>
 * @since swing-extras 2.8 (refactored from older code)
 */
class TabPanePropertiesDialog extends PropertiesDialog {

    private static final Logger logger = Logger.getLogger(TabPanePropertiesDialog.class.getName());

    private ToggleableTabbedPane tabbedPane;
    private final boolean alwaysShowSubcategoryLabels;

    public TabPanePropertiesDialog(Window owner, String title, List<AbstractProperty> properties, boolean alwaysShowSubcategoryLabels) {
        super(owner, title, properties);
        this.alwaysShowSubcategoryLabels = alwaysShowSubcategoryLabels;
    }

    /**
     * In this PropertiesDialog implementation, we treat every top-level category as a separate tab,
     * and we show header labels for the subcategories within each tab. You can control whether
     * subcategory labels should be shown in the case where there's only one subcategory (which would be
     * redundant with the tab header) by setting the alwaysShowSubcategoryLabels flag in the constructor.
     */
    @Override
    protected void populateFormPanels() {
        for (String category : categories) {
            List<String> subCategories = subcategoriesByCategory.get(category);
            FormPanel formPanel = new FormPanel(DEFAULT_ALIGNMENT);
            formPanel.setBorderMargin(DEFAULT_BORDER_MARGIN);
            formPanel.setName(category); // this controls the label for the tab header
            for (String subCategory : subCategories) {
                // Show a subcategory label header if there's more than one subcategory:
                if (subCategories.size() > 1 || alwaysShowSubcategoryLabels) {
                    FormField field = LabelProperty
                            .createHeaderLabel(category + "." + subCategory + ".autoGeneratedHeaderLabel", subCategory)
                            .generateFormField(formPanel);
                    formPanel.add(field);
                }

                // Show all the properties in this subcategory:
                List<AbstractProperty> propList = PropertiesManager.getProperties(properties, category, subCategory);
                for (AbstractProperty prop : propList) {
                    try {
                        FormField field = prop.generateFormField(formPanel);
                        formPanel.add(field);
                    }
                    catch (UnsupportedOperationException use) {
                        // In VERY rare cases, a property might not support FormField generation.
                        // In that case, we'll just skip it and log a warning:
                        // (ideally such a property would never be added in the first place, but let's be safe)
                        logger.warning("Property \""
                                               + prop.getFullyQualifiedName()
                                               + "\" does not support FormField generation. Skipping.");
                    }
                }
            }
            formPanels.add(formPanel);
        }
    }

    /**
     * Lay out our FormPanels into our tabbed pane.
     */
    @Override
    protected void initLayout() {
        tabbedPane = new ToggleableTabbedPane();
        for (FormPanel formPanel : formPanels) {
            tabbedPane.addTab(formPanel.getName(), ScrollUtil.buildScrollPane(formPanel));
        }

        // If there's only one FormPanel, let's toggle the tab header row off:
        if (formPanels.size() == 1) {
            tabbedPane.setTabHeaderVisible(false);
        }

        add(tabbedPane, BorderLayout.CENTER);
    }

    /**
     * Activates the tab that represents the given FormPanel.
     * This is invoked by the parent class to show validation errors.
     *
     * @param formPanel The FormPanel that should be made visible.
     */
    @Override
    protected void makeFormPanelVisible(FormPanel formPanel) {
        // We built tabs using the same order as we populated the formPanels list,
        // so if we find the correct index in formPanels, we can just use that
        // index to set the selected tab in the tabbed pane:
        for (int i = 0; i < formPanels.size(); i++) {
            FormPanel fp = formPanels.get(i);
            if (fp == formPanel) {
                tabbedPane.setSelectedIndex(i);
                return;
            }
        }
    }
}
